split1:
    experiment_name: tumor_grade_x5_256_mobilenet_v2_without_es_1
    batch_size: 32
    validation_interval: 50
    epochs: 10
    subtypes:
      - G1=0
      - G2=1
      - G3=2
    patch_pattern: subtype/slide
    chunk_file_location: /home/poahmadvand/share/Sub_Types/03_Create_Cross_Validation_Groups/tumor_grade_x5_256/split.1_2_train_3_eval.json
    log_dir_location: /projects/ovcare/classification/pouya/models/subtypes/X5_256/tumor_grade/tumor_grade_x5_256_mobilenet_v2/logs/train
    model_dir_location: /projects/ovcare/classification/pouya/models/subtypes/X5_256/tumor_grade/tumor_grade_x5_256_mobilenet_v2/weights
    model_config_location: /home/poahmadvand/share/Sub_Types/04_Train_Model/model_config/tumor_grade.json
    patch_location: /projects/ovcare/classification/Diagnostic_TCGA_PDAC_cases/subtypes/X5_512/tumor_grade
    num_patch_workers: 3
    writer_log_dir_location: /projects/ovcare/classification/pouya/models/subtypes/X5_256/tumor_grade/tumor_grade_x5_256_mobilenet_v2/logs/train/tensorboard
    early_stopping:
      use_early_stopping: False
      patience: 7
      delta: 0
    test_model:
      testing_model: True
      test_log_dir_location: /projects/ovcare/classification/pouya/models/subtypes/X5_256/tumor_grade/tumor_grade_x5_256_mobilenet_v2/logs/test
      detailed_test_result:
split2:
    experiment_name: tumor_grade_x5_256_mobilenet_v2_without_es_2
    batch_size: 32
    validation_interval: 50
    epochs: 10
    subtypes:
      - G1=0
      - G2=1
      - G3=2
    patch_pattern: subtype/slide
    chunk_file_location: /home/poahmadvand/share/Sub_Types/03_Create_Cross_Validation_Groups/tumor_grade_x5_256/split.1_3_train_2_eval.json
    log_dir_location: /projects/ovcare/classification/pouya/models/subtypes/X5_256/tumor_grade/tumor_grade_x5_256_mobilenet_v2/logs/train
    model_dir_location: /projects/ovcare/classification/pouya/models/subtypes/X5_256/tumor_grade/tumor_grade_x5_256_mobilenet_v2/weights
    model_config_location: /home/poahmadvand/share/Sub_Types/04_Train_Model/model_config/tumor_grade.json
    patch_location: /projects/ovcare/classification/Diagnostic_TCGA_PDAC_cases/subtypes/X5_512/tumor_grade
    num_patch_workers: 3
    writer_log_dir_location: /projects/ovcare/classification/pouya/models/subtypes/X5_256/tumor_grade/tumor_grade_x5_256_mobilenet_v2/logs/train/tensorboard
    early_stopping:
      use_early_stopping: False
      patience: 7
      delta: 0
    test_model:
      testing_model: True
      test_log_dir_location: /projects/ovcare/classification/pouya/models/subtypes/X5_256/tumor_grade/tumor_grade_x5_256_mobilenet_v2/logs/test
      detailed_test_result:
split3:
    experiment_name: tumor_grade_x5_256_mobilenet_v2_without_es_3
    batch_size: 32
    validation_interval: 50
    epochs: 10
    subtypes:
      - G1=0
      - G2=1
      - G3=2
    patch_pattern: subtype/slide
    chunk_file_location: /home/poahmadvand/share/Sub_Types/03_Create_Cross_Validation_Groups/tumor_grade_x5_256/split.2_3_train_1_eval.json
    log_dir_location: /projects/ovcare/classification/pouya/models/subtypes/X5_256/tumor_grade/tumor_grade_x5_256_mobilenet_v2/logs/train
    model_dir_location: /projects/ovcare/classification/pouya/models/subtypes/X5_256/tumor_grade/tumor_grade_x5_256_mobilenet_v2/weights
    model_config_location: /home/poahmadvand/share/Sub_Types/04_Train_Model/model_config/tumor_grade.json
    patch_location: /projects/ovcare/classification/Diagnostic_TCGA_PDAC_cases/subtypes/X5_512/tumor_grade
    num_patch_workers: 3
    writer_log_dir_location: /projects/ovcare/classification/pouya/models/subtypes/X5_256/tumor_grade/tumor_grade_x5_256_mobilenet_v2/logs/train/tensorboard
    early_stopping:
      use_early_stopping: False
      patience: 7
      delta: 0
    test_model:
      testing_model: True
      test_log_dir_location: /projects/ovcare/classification/pouya/models/subtypes/X5_256/tumor_grade/tumor_grade_x5_256_mobilenet_v2/logs/test
      detailed_test_result:
