try_me:
    experiment_name: tumor_grade_x5_256_vgg19_without_normalization_1
    batch_size: 32
    validation_interval: 50
    epochs: 10
    subtypes:
      - G1=0
      - G2=1
      - G3=2
    patch_pattern: subtype/slide
    chunk_file_location: /home/poahmadvand/share/Sub_Types/03_Create_Cross_Validation_Groups/tumor_grade_x5_256/split.1_2_train_3_eval.json
    log_dir_location: /projects/ovcare/classification/pouya/models/subtypes/tumor_grade/tumor_grade_x5_256_vgg19_without_normalization/logs/train
    model_dir_location: /projects/ovcare/classification/pouya/models/subtypes/tumor_grade/tumor_grade_x5_256_vgg19_without_normalization/weights
    model_config_location: /home/poahmadvand/share/Sub_Types/04_Train_Model/model_config/vgg19_3c_bn__n2__adam__lr_0_0002.json
    number_of_gpus: 4
    num_patch_workers: 3
    writer_log_dir_location: /projects/ovcare/classification/pouya/models/subtypes/tumor_grade/tumor_grade_x5_256_vgg19_without_normalization/logs/train/tensorboard
    early_stopping:
      use_early_stopping: True
      patience: 7
      delta: 0
    test_model:
      testing_model: True
      test_log_dir_location: /projects/ovcare/classification/pouya/models/subtypes/tumor_grade/tumor_grade_x5_256_vgg19_without_normalization/logs/test
      detailed_test_result:
