try_me:
    experiment_name: TMA_EC_4_subtypes_3_groups_512_20x_patch_overlap_0.8_annotation_overlap_0.5.1_3_train_2_eval_vgg19bn_CEloss_Simple
    batch_size: 32
    validation_interval: -1
    epochs: 5
    patch_pattern: annotation/subtype/slide/patch_size/magnification
    chunk_file_location: /projects/ovcare/classification/amirali/ML/TMA/OneStage/SubType/03_Create_Cross_Validation_Groups/TMA_EC_4_subtypes_3_groups_512_20x_patch_overlap_0.8_annotation_overlap_0.5.1_3_train_2_eval.json
    log_dir_location: /projects/ovcare/classification/amirali/ML/TMA/OneStage/SubType/04_Train/logs/train
    model_dir_location: /projects/ovcare/classification/amirali/ML/TMA/OneStage/SubType/04_Train/model
    model_config_location: /projects/ovcare/classification/amirali/ML/TMA/OneStage/SubType/04_Train/model/config.json
    train_model: True
    # scheduler_step: batch
    subtypes:
        - MMRD=0
        - P53ABN=1
        - P53WT=2
        - POLE=3
    training_shuffle:
    num_patch_workers: 4
    # progressive_resizing: [62, 128, 512]
    number_of_gpus: 1
    freeze_training:
        use_freeze_training: False
        freeze_epochs: 1
        unfreeze_epochs: 4
        base_lr: 0.00006
        lr_mult: 1
        # use_scheduler:
    early_stopping:
        use_early_stopping: False
        patience: 7
        delta: 0
    test_model:
        testing_model: True
        # test_model_file_location: /projects/ovcare/classification/amirali/ML/TMA/OneStage/SubType/04_Train/model/TMA_EC_2_subtypes_p53abn_p53wt_3_groups_512_10x_patch_overlap_0.8_annotation_overlap_0.5_1_3_train_2_eval_efficientnet_b0_CEloss_lr00002_20210312-003750.pth
        test_log_dir_location: /projects/ovcare/classification/amirali/ML/TMA/OneStage/SubType/04_Train/logs/test
        detailed_test_result: ~
        calculate_slide_level_accuracy:
